[package]
name = "ifmon"
version = "0.1.0"
description = "A beautiful terminal-based network interface monitoring tool"
authors = ["coder3101 <ashar786khan@gmail.com>"]
license = "MIT"
edition = "2021"
repository = "https://github.com/coder3101/ifmon"
keywords = ["network", "monitoring", "tui", "terminal", "interface"]
categories = ["command-line-utilities", "network-programming"]
readme = "README.md"
exclude = ["assets/"]

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.0"
color-eyre = "0.6.3"
netdev = "0.46.2"
unicode-width = "0.2"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
